Feature/future target
mdamonte88/react-redux-target pull request #8
Opened 2018-12-13 20:29 UTC by mdamonte88

(3) As a user, I should be able to see a map so I can easily identify targets in the future

**Story**
![image](https://user-images.githubusercontent.com/4093354/49965674-a0ee8500-fefc-11e8-8247-60e0b9db450e.png)

**Pull Request**
![image](https://user-images.githubusercontent.com/4093354/49966172-0c852200-fefe-11e8-829b-dc1927f7f216.png)

2018-12-14 12:40 UTC, lunemmer reviewed
Great work. I left some comments!

2018-12-14 12:40 UTC, lnemmer commented on src/actions/targetActions.js
> +      dispatch(deleteTargetSuccess({}, -1));
Why are you passing an empty object and -1?
Also, I saw that you are repeating `deleteTargetSuccess({}, -1)` in other files, so maybe it's better declare deleteTargetSuccess function as `deteleTargetSuccess(index = -1, target = {})` and call it in other line as:
`deleteTargetSuccess()`
`deleteTargetSuccess(index)`
`deleleTargetSuccess(index, targetResponse) `

2018-12-14 12:40 UTC, lnemmer commented on src/actions/targetActions.js
> +      dispatch(deleteTargetSuccess({}, index));
I think that you should change function name because you're calling `deleteTargetSuccess` when the call to the API threw an error, it's confusing.

2018-12-14 12:40 UTC, lnemmer commented on src/styles/sign-up-page.scss
> +      height: 100px;
Use `rem` instead of `px`

2018-12-14 12:40 UTC, lnemmer commented on src/styles/sign-up-page.scss
> +    margin-right: 10px;
Same

2018-12-17 13:17 UTC, xlasserre requested changes
Nice job! Left one comment

2018-12-17 13:17 UTC, xlasserre commented on src/actions/targetActions.js
> +      dispatch(deleteTargetSuccess({}, index));
Yeah, I agree with this. You should change the name of the function.

2018-12-18 15:39 UTC, agch-dev reviewed
Nice work! just some comments

2018-12-18 15:39 UTC, aguscha333 commented on src/components/common/maps/markers/Point.js
> +    const {
put this in one line and remove trailing comma

2018-12-18 15:39 UTC, aguscha333 commented on src/styles/sign-up-page.scss
> +    background-color: rgba(255, 255, 255, 0.7);
put colors in constants file you can then do: `rgba($white, .7)`. If you think that you are going to use this color with that alpha often you should put the color with the alpha in the constants file. Same for the other hardcoded colors in the file.
There is also no need for the 0 when writing decimals just `.7` will do.

2018-12-18 15:41 UTC, felipegarcia92 requested changes

2018-12-18 15:41 UTC, felipegarcia92 commented on src/components/common/maps/markers/Point.js
> +export default class PointMarket extends PureComponent {
I think you have a typo here, `PointMarker`

2018-12-18 15:41 UTC, felipegarcia92 commented on src/components/common/maps/markers/Point.js
> +  render() {
You can convert this to a stateless component. https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

2018-12-18 15:41 UTC, felipegarcia92 commented on src/reducers/targetReducer.js
> +      const lastTarget = (state.get('targetList').size > 0 ? state.getIn(['targetList', -1]).toJS() : {}).target;
You get a target from the action right?

There's no need to control if you have any target in the list, and if that target is a future target or whatever. Just replace it.

`return state.setIn(['targetList', -1], target)`

2018-12-18 15:41 UTC, felipegarcia92 commented on src/reducers/targetReducer.js
> +      const lastTarget = (state.get('targetList').size > 0 ? state.getIn(['targetList', -1]).toJS() : {}).target;
Same here. Maybe you can check if you have a -1 index so no undefined errors appear, but doing something like this should be enough:

`if (state.get('targetList').has(-1)) { state.getIn(['targetList']).remove(-1) }`

2018-12-19 19:04 UTC, agch-dev approved these changes

2018-12-19 19:05 UTC, xlasserre approved these changes

2018-12-19 20:02 UTC, felipegarcia92 approved these changes

2018-12-20 12:44 UTC, lunemmer approved these changes

2018-12-20 13:58 UTC, alealvarez14 approved these changes

2018-12-20 14:32 UTC, merged